// uses inquirer to run the prompts
const inquirer = require('inquirer');
// uses file system so we can use associated functions
const fs = require('fs');
// call class constructor files
const Manager = require('./lib/Manager');
const Engineer = require('./lib/Engineer');
const Intern = require('./lib/Intern');

// Initialize array of all employees generated by user
employees = [];

// Initiate prompt
managerPrompts();

// list of prompts for manager
function managerPrompts() {
    inquirer.prompt([
        {
            type: 'input',
            message: 'Please enter your team Manager\'s Name (e.g. David Hasselhoff):',
            name: 'name',
        },
        {
            type: 'input',
            message: 'Please enter your team Manager\'s employee id (e.g. 1):',
            name: 'id',
        },
        {
            type: 'input',
            message: 'Please enter your team Manager\'s email address (e.g. DHasselhoff@aim.com):',
            name: 'email',
        },
        {
            type: 'input',
            message: 'Please enter your team Manager\'s office number (e.g. 240):',
            name: 'officeNumber',
        },
    ])
        // constructs new manager with user inputs and pushes it to an array of all employees generated
        .then(({ name, id, email, officeNumber }) => {
            employees.push(new Manager(name, id, email, officeNumber));
            nextAction();
        });
}

// list of prompts for engineer
function engineerPrompts() {
    inquirer.prompt([
        {
            type: 'input',
            message: 'Please enter your Engineers\'s Name (e.g. David Hasselhoff):',
            name: 'name',
        },
        {
            type: 'input',
            message: 'Please enter your Engineers\'s employee id (e.g. 1):',
            name: 'id',
        },
        {
            type: 'input',
            message: 'Please enter your Engineers\'s email address (e.g. DHasselhoff@aim.com):',
            name: 'email',
        },
        {
            type: 'input',
            message: 'Please enter your Engineers\'s GitHub username (e.g. DHasselhoff):',
            name: 'github',
        },
    ])
        // constructs new engineer with user inputs and pushes it to an array of all employees generated
        .then(({ name, id, email, github }) => {
            employees.push(new Engineer(name, id, email, github));
            nextAction();
        });
}

// list of prompts for interns
function internPrompts() {
    inquirer.prompt([
        {
            type: 'input',
            message: 'Please enter your Interns\'s Name (e.g. David Hasselhoff):',
            name: 'name',
        },
        {
            type: 'input',
            message: 'Please enter your Interns\'s employee id (e.g. 1):',
            name: 'id',
        },
        {
            type: 'input',
            message: 'Please enter your Interns\'s email address (e.g. DHasselhoff@aim.com):',
            name: 'email',
        },
        {
            type: 'input',
            message: 'Please enter your Interns\'s school (e.g. Bates College):',
            name: 'school',
        },
    ])
        // constructs new intern with user inputs and pushes it to an array of all employees generated
        .then(({ name, id, email, school }) => {
            employees.push(new Intern(name, id, email, school));
            nextAction();
        });
}

function nextAction() {
    inquirer.prompt([
        {
            type: 'list',
            message: 'Please choose the next type of employee you would like to enter, if any:',
            choices:
                [
                    'Engineer',
                    'Intern',
                    'Finish Team',
                ],
            name: 'action',
        }
    ])
        // determines next action based on user input
        .then(({ action }) => {
            if (action === 'Engineer') {
                engineerPrompts();
            } else if (action === 'Intern') {
                internPrompts();
            } else {
                process.exit();
                writeHTML(employees);
            }
        });
}

function writeHTML(employees) {
    // Write the following text to a new html file
    console.log(employees);
    fs.writeFile('/dist/team.html', 
    ``
    
    , err =>
        err ? console.error(err) : console.log('Generating Web page...'))

}





    // icebox:
// {
//     type: 'input',
//     message: 'Please enter your team name (e.g. Team Hasselhoff):',
//     name: 'teamName',
// },
// store all prompts in separate file and export in, destructure on import and call in specific functions
// store html in separate file and export in to writeHTML function